services:
    git_delete_stale_branches:
        build:
            args:
                - BUILD_DATE
                - GIT_COMMIT
                - GIT_COMMIT_DATE
                - PROJECT
                - USER_GID
                - USER_UID
            context: .
            network: host
        entrypoint: ''
        stdin_open: true
        tty: true
        volumes:
            -   read_only: false
                source: ${ROOT_DIR}/other
                target: /home/ubuntu_user/git_delete_stale_branches/other
                type: bind
version: '3.3'
