#! /usr/bin/env bash
#
# Parse CLI arguments defined in a recfile and put them in an associative
# array.

function is_docker() {
    local cgroup=/proc/1/cgroup
    test -f "$cgroup"
    grep -E ':cpuset:/docker' -- "$cgroup" > /dev/null 2>&1
}

function is_valid_simple_csv() {
    local is_valid=true
}

function validate_number_of_arguments() {
    _validate_number_of_arguments ${@} 2
    local expected_number_of_arguments="${1}"
    local error_message="${2}"
    if _validate_number_of_arguments ${@} "${expected_number_of_arguments}"; then
        echo "${error_message}" 2>&1
        return 1
    fi
}

function _validate_number_of_arguments() {
    # Get the number of arguments excluding the last one
    local n_args_received=$(($# - 1))
    # Get the last argument
    local n_args_expected="${!#}"

    if ((n_args_received != n_args_expected)); then
        return 1
    fi
}

# vim: set filetype=sh fileformat=unix nowrap:
