#! /usr/bin/env bash

# Halt on error.
set -euxo pipefail

# function git_check_branch_exists() {
#   git rev-parse --verify <branch_name>
# }

# Go to execution directory.
cd "$(dirname $(readlink -f "${0}"))"

sudo dpkg -i /opt/deb/*.deb

bash -xv ./docker_test_01

bash -xv ./docker_test_02

echo "Success." > /dev/stderr
exit 0

# vim: set filetype=sh fileformat=unix nowrap:
