#! /usr/bin/env bash

# Halt on error.
set -euo pipefail

# Go to execution directory.
cd "$(dirname $(readlink -f "${0}"))"

sudo dpkg -i /opt/deb/*.deb

bash -xv ./docker_test_01

bash -xv ./docker_test_02

echo "Success." > /dev/stderr
exit 0

# vim: set filetype=sh fileformat=unix nowrap:
