#! /usr/bin/env bash

# Halt on error.
set -euo pipefail

# Go to execution directory.
{ cd "$(dirname $(readlink -f "${0}"))" && git rev-parse --is-inside-work-tree > /dev/null 2>&1 && cd "$(git rev-parse --show-toplevel)"; } || cd "$(dirname "$(readlink -f ${0})")"
# Close identation: }

bash ./other/test/docker/host_test_01

bash ./other/test/docker/host_test_02

bash ./other/test/docker/host_test_03

# vim: set filetype=sh fileformat=unix nowrap:
