#! /usr/bin/env bash

# Halt on error.
set -euo pipefail

# Go to execution directory.
cd "$(git rev-parse --show-toplevel)"

bash ./other/test/docker/host_test_01

bash ./other/test/docker/host_test_02

bash ./other/test/docker/host_test_03

bash ./other/test/test_library/test_01.sh

# vim: set filetype=sh fileformat=unix nowrap:
